[package]
name = "qango-rest"
version = "0.1.0"
authors = ["klaus@itzgrund.net"]
edition = "2018"

[dependencies]
actix-web = "2.0"
actix-rt = "1.0"
listenfd = "0.3"
serde = "1.0"
serde_json = "1.0"
qango = { path = "../qango" }
futures = "0.3"
