[package]
name = "qango-rest"
version = "0.1.0"
authors = ["klaus@itzgrund.net"]
edition = "2018"

[dependencies]
actix-web = "3"
actix-files = "0.4"
log = "0.4"
env_logger="0.8"
serde = "1.0"
serde_json = "1.0"
qango = { path = "../qango" }
futures = "0.3"
